version: '2'
services:
  mysql-portal:
    image: dregistry.icetana.com.au/mysql-portal
    restart: always
    ports:
      - 3306:3306
  djreact-portal:
    image: dregistry.icetana.com.au/djreact-portal
    ports:
     - "8000:8000"
