export const DEFAULT_LOCALE = 'en';
export const CONFIG_REQUEST_INIT = 'app/CONFIG_REQUEST_INIT';
export const CONFIG_REQUEST_SUCCESS = 'app/CONFIG_REQUEST_SUCCESS';
export const CONFIG_REQUEST_FAILURE = 'app/CONFIG_REQUEST_FAILURE';
