export const DEFAULT_LOCALE = 'en';
export const CONFIG_REQUEST_INIT = 'app/CONFIG_REQUEST_INIT';
export const CONFIG_REQUEST_SUCCESS = 'app/CONFIG_REQUEST_SUCCESS';
export const CONFIG_REQUEST_FAILURE = 'app/CONFIG_REQUEST_FAILURE';
export const CAMERA_FILTERS_UPDATE_INIT = 'app/CAMERA_FILTERS_UPDATE_INIT';
export const CAMERA_FILTERS_UPDATE_SUCCESS = 'app/CAMERA_FILTERS_UPDATE_SUCCESS';
export const CAMERA_FILTERS_UPDATE_FAILURE = 'app/CAMERA_FILTERS_UPDATE_FAILURE'