/*
 *
 * Auth constants
 *
 */

export const LIVEWALL_UPDATE_CAMERAFILTER = 'app/LiveWall/LIVEWALL_UPDATE_CAMERAFILTER';
export const LIVEWALL_CLEAR_CAMERAFILTER = 'app/LiveWall/LIVEWALL_CLEAR_CAMERAFILTER';
export const LIVEWALL_TOGGLE_FULLSCREEN = 'app/LiveWallFullScreen/LIVEWALL_TOGGLE_FULLSCREEN';
