export const DEFAULT_LOCALE = 'en';
export const COUNTRIES_REQUEST_INIT = 'app/Home/COUNTRIES_REQUEST_INIT';
export const COUNTRIES_REQUEST_SUCCESS = 'app/Home/COUNTRIES_REQUEST_SUCCESS';
export const COUNTRIES_REQUEST_FAILURE = 'app/Home/COUNTRIES_REQUEST_FAILURE';
