/*
 *
 * TeacherPackage constants
 *
 */

export const DEFAULT_ACTION = 'app/TeacherPackage/DEFAULT_ACTION';
export const TEACHER_SELECT_PACKAGE = 'app/TeacherPackage/TEACHER_SELECT_PACKAGE';
export const UPDATE_TEACHER_PACKAGE_FIRSTNAME = 'app/TeacherPackage/UPDATE_TEACHER_PACKAGE_FIRSTNAME';
export const UPDATE_TEACHER_PACKAGE_LASTNAME = 'app/TeacherPackage/UPDATE_TEACHER_PACKAGE_LASTNAME';
export const UPDATE_TEACHER_PACKAGE_EMAIL = 'app/TeacherPackage/UPDATE_TEACHER_PACKAGE_EMAIL';
export const UPDATE_TEACHER_PACKAGE_PASSWORD = 'app/TeacherPackage/UPDATE_TEACHER_PACKAGE_PASSWORD';
export const UPDATE_TEACHER_PACKAGE_PASSWORDCONFIRM = 'app/TeacherPackage/UPDATE_TEACHER_PACKAGE_PASSWORDCONFIRM';
export const UPDATE_TEACHER_PACKAGE_TERMS = 'app/TeacherPackage/UPDATE_TEACHER_PACKAGE_TERMS';
