export const LOAD_CAMERA_LIST_INIT = 'config/LOAD_CAMERA_LIST_INIT';
export const LOAD_CAMERA_LIST_SUCCESS = 'config/LOAD_CAMERA_LIST_SUCCESS';
export const LOAD_CAMERA_LIST_FAILURE = 'config/LOAD_CAMERA_LIST_FAILURE';
