/*
 *
 * SchoolPackage constants
 *
 */

export const DEFAULT_ACTION = 'app/SchoolPackage/DEFAULT_ACTION';
export const SCHOOL_SELECT_PACKAGE = 'app/SchoolPackage/SCHOOL_SELECT_PACKAGE';
export const UPDATE_SCHOOL_PACKAGE = 'app/SchoolPackage/UPDATE_SCHOOL_PACKAGE';
export const UPDATE_SCHOOL_PACKAGE_COUNTRY = 'app/SchoolPackage/UPDATE_SCHOOL_PACKAGE_COUNTRY';
export const UPDATE_SCHOOL_PACKAGE_NUMBERSTUDENTS = 'app/SchoolPackage/UPDATE_SCHOOL_PACKAGE_NUMBERSTUDENTS';
export const UPDATE_SCHOOL_PACKAGE_TUITIONFEES = 'app/SchoolPackage/UPDATE_SCHOOL_PACKAGE_TUITIONFEES';
export const UPDATE_SCHOOL_PACKAGE_JOBLISTING = 'app/SchoolPackage/UPDATE_SCHOOL_PACKAGE_JOBLISTING';
export const UPDATE_SCHOOL_PACKAGE_IBDP = 'app/SchoolPackage/UPDATE_SCHOOL_PACKAGE_IBDP';
export const SCHOOL_PACKAGE_QUOTE_INIT = 'app/SchoolPackage/SCHOOL_PACKAGE_QUOTE_INIT';
export const SCHOOL_PACKAGE_QUOTE_SUCCESS = 'app/SchoolPackage/SCHOOL_PACKAGE_QUOTE_SUCCESS';
export const SCHOOL_PACKAGE_QUOTE_FAILURE = 'app/SchoolPackage/SCHOOL_PACKAGE_QUOTE_FAILURE';
